In [1]:
"""
Simple TensorFlow exercises
You should thoroughly test your code
"""

import tensorflow as tf
from tensorflow.python.client import device_lib

def get_available_gpus():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos if x.device_type == 'GPU']

get_available_gpus()

[]

In [2]:
sess = tf.InteractiveSession()

In [3]:

###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

x = tf.random_uniform([])  # Empty array as shape creates a scalar.
y = tf.random_uniform([])
out = tf.cond(tf.less(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))

print(x)
print(y)
print(out)

print(x.eval())
print(y.eval())
print(out.eval())

Tensor("random_uniform:0", shape=(), dtype=float32)
Tensor("random_uniform_1:0", shape=(), dtype=float32)
Tensor("cond/Merge:0", shape=(), dtype=float32)
0.122447
0.0185324
0.336029


In [4]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from -1 and 1.
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x = tf.random_normal([])
y = tf.random_normal([])
out = tf.case([(tf.less(x, y), lambda: x + y),(tf.greater(x, y), lambda: x - y)],
              default = lambda: tf.constant(0.0), exclusive=False)

print(x)
print(y)
print(out)

print(x.eval())
print(y.eval())
print(out.eval())

Tensor("random_normal:0", shape=(), dtype=float32)
Tensor("random_normal_1:0", shape=(), dtype=float32)
Tensor("case/If_2/Merge:0", shape=(), dtype=float32)
0.731768
0.248398
2.16609


In [5]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
out = tf.equal(x,y)

print(x)
print(y)
print(out)

print(x.eval())
print(y.eval())
print(out.eval())

Tensor("Const:0", shape=(2, 3), dtype=int32)
Tensor("zeros_like:0", shape=(2, 3), dtype=int32)
Tensor("Equal:0", shape=(2, 3), dtype=bool)
[[ 0 -2 -1]
 [ 0  1  2]]
[[0 0 0]
 [0 0 0]]
[[ True False False]
 [ True False False]]


In [6]:

###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################

x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858])
greater_than30 = tf.greater(x, 30)
indices = tf.where(greater_than30)
out = tf.gather(x,indices)

print(greater_than30)
print(indices)
print(out)

print(greater_than30.eval())
print(indices.eval())
print(out.eval())



Tensor("Greater_1:0", shape=(20,), dtype=bool)
Tensor("Where:0", shape=(?, 1), dtype=int64)
Tensor("Gather:0", shape=(?, 1), dtype=float32)
[False False  True False  True False  True False  True  True False  True
 False False  True False  True False  True False]
[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [7]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################

x = tf.range(1,6,1)
out = tf.diag(x)

print(x)
print(out)

print(x.eval())
print(out.eval())

Tensor("range:0", shape=(5,), dtype=int32)
Tensor("Diag:0", shape=(5, 5), dtype=int32)
[1 2 3 4 5]
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [8]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################

x = tf.truncated_normal((10,10))
out = tf.matrix_determinant(x)

print(x)
print(out)

print(x.eval())
print(out.eval())

Tensor("truncated_normal:0", shape=(10, 10), dtype=float32)
Tensor("MatrixDeterminant:0", shape=(), dtype=float32)
[[ 0.64653373 -0.82647288 -0.57400352 -0.0273181   0.89112407  0.08645537
   0.37327883  0.58986479 -1.36013079 -0.74957061]
 [-0.5618791   0.62175232  1.62743104 -0.11022266 -0.43921256  1.34618127
  -0.27526298  0.31541416 -1.88808894 -0.60268497]
 [ 0.03368518 -0.97702754 -0.99207354 -0.59374589  1.04063904 -0.80095482
   1.26582468 -0.16921182 -1.57477367  1.12872088]
 [ 1.58183455 -0.09781016  0.44485039  0.14942671 -0.52645093 -0.94721639
  -0.03658967  1.26401627 -0.46355346 -0.35541767]
 [ 1.13661385  1.0301342  -0.07634027 -0.6200788  -0.13108951 -0.40944314
  -0.39955032  0.51810586 -1.49995136  1.86608064]
 [-0.95153445 -1.12926173  1.19234002 -0.15195356 -0.45872477  0.43553036
  -0.0648866   1.3024478   0.61720854  0.62003875]
 [ 0.14888848  0.21174584 -0.31933883  0.53892964  0.80018824  0.49448332
   0.2458992  -0.98361909 -0.70389634  1.36853981]
 [ 0.97353

In [9]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################

x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
out, idx = tf.unique(x)

print(x)
print(out)
print(idx)

print(x.eval())
print(out.eval())
print(idx.eval())

Tensor("Const_2:0", shape=(14,), dtype=int32)
Tensor("Unique:0", shape=(?,), dtype=int32)
Tensor("Unique:1", shape=(14,), dtype=int32)
[ 5  2  3  5 10  6  2  3  4  2  1  1  0  9]
[ 5  2  3 10  6  4  1  0  9]
[0 1 2 0 3 4 1 2 5 1 6 6 7 8]


In [10]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.less() and tf.select() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################

x = tf.random_normal([300])
y = tf.random_normal([300])
diff = tf.subtract(x,y)
mean = tf.reduce_mean(diff)
mean_square = tf.square(mean)
diff_sum = tf.reduce_sum(tf.abs(diff))
out = tf.where(tf.less(mean,0), mean_square, diff_sum)

print(x)
print(y)
print(diff)
print(mean)
print(diff_sum)
print(out)

print(x.eval())
print(y.eval())
print(diff.eval())
print(mean.eval())
print(diff_sum.eval())
print(out.eval())

Tensor("random_normal_2:0", shape=(300,), dtype=float32)
Tensor("random_normal_3:0", shape=(300,), dtype=float32)
Tensor("Sub:0", shape=(300,), dtype=float32)
Tensor("Mean:0", shape=(), dtype=float32)
Tensor("Sum:0", shape=(), dtype=float32)
Tensor("Select:0", shape=(), dtype=float32)
[-0.08290772 -0.27966785  1.36846066  0.32212222  0.2836791   0.43802658
 -1.07712758 -2.21481371 -0.76852179 -0.50340009  0.73801947  1.04254866
 -0.14306183 -0.15324666  0.5756613   0.13135363 -0.52031046  0.87954986
 -0.38819361  1.60124683  0.45508772 -0.97009963  0.1585509  -0.89860749
  0.23470041 -0.70059675 -2.14492965 -1.30437148 -0.48742178 -2.1757412
 -0.04269007  0.8011328  -0.79681242  0.1296555  -0.10951829 -1.25135207
  1.00486934  0.77617931 -1.0897944  -1.2796849   0.87173384  1.43731749
 -0.9523443  -0.24857475  0.62761635 -1.40048015  0.42612666  0.43046647
 -1.47708845  0.24100351  0.51118004 -0.72392464 -1.29221928  0.1233277
  0.58588642  1.71553493  1.02544224 -0.03144473  0.2984418

In [11]:
sess.close()